### PR TITLE
Replace \\ in description attributes with /

### LINKED ISSUE #174: Replace `\` in description attributes with `/`

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #174 

`\\` in description attributes has been replaced with `/` as there are issues with json during beta deployment.

### CODE REVIEW

**Comment by Tom-Kingstone** [comment]
@BHoMBot check core
@BHoMBot check compliance

**Comment by Tom-Kingstone** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
This will make life slightly easier on the end of milestone side, thanks @Tom-Kingstone

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Comment by Tom-Kingstone** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
