### PR TITLE
Changed default Push Type to `DeleteThenCreate`

### LINKED ISSUE #123: Change the default PushType to `DeleteThenCreate`
#### Description:

As discussed with @kayleighhoude and others, it makes little sense to have the default behaviour of the FileAdapter to "update" the content of the file by "appending". Given the 99% of the cases the FileAdapter is used to dump JSON files – but this would be true anyway – the default behaviour should be of re-creating the file. The "appending" behaviour is also very file extension-specific, so it's risky to have it as a default.

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #123 

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/Eqphw7WXhFxLo8jBjH0JDPQBE4wrMVQuHae6MPuxI3Gqpg?e=G3ygW6

### Changelog

- Changed default Push Type from `UpdateOrCreateOnly` to `DeleteThenCreate`

### CODE REVIEW

**Review by kayleighhoude — APPROVED** [review]
Perfect! Default JSON behaviour is to delete then create, anything else and you'll trip over yourself!

**Comment by FraserGreenroyd** [comment]
> ### Test files
> Not needed.

I strongly beg to differ...

**Comment by alelom** [comment]
> I strongly beg to differ...

@FraserGreenroyd I regretted typing that as soon as I finished, but it was late - updated

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
> @FraserGreenroyd I regretted typing that as soon as I finished, but it was late - updated

Much better 😉

**Comment by alelom** [comment]
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance

**Comment by alelom** [comment]
@BHoMBot check required
@BHoMBot check ready-to-merge

**Comment by alelom** [comment]
@BHoMBot check dataset-compliance 
@BHoMBot check copyright-compliance

**Review by kayleighhoude — APPROVED** [review]
Agree with these changes

**Comment by alelom** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
