### PR TITLE
Fix project file

### LINKED ISSUE #166: BaseOutputPath is not valid
Should be `OutputPath`.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #166

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by travispotterBH — APPROVED** [review]
Necessary for bot.

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: core, installer, null-handling, ready-to-merge, serialisation, versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Pull request merged**
