### PR TITLE
Upgrade to .NetStandard2.0

### LINKED ISSUE #151: Upgrade to .NetStandard2.0
In line with other toolkits close to the core.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #151

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 12058714353

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Review by adecler — CHANGES_REQUESTED** [review]
Doesn't run correctly:
image

Let me guess: forgot to copy the new reference to the Assembly folder ? 😉

**Review by adecler — CHANGES_REQUESTED** [review]
The file owner extraction stopped working with this PR.

Here's from the main: 
image

Same script with this PR:
image

**Comment by alelom** [comment]
I can replicate what @adecler describes when running FileAdapter from Rhino.

The captured exception is: `System.PlatformNotSupportedException: 'Access Control List (ACL) APIs are part of resource management on Windows and are not supported on this platform.'`, thrown in [AddExtradata](https://github.com/BHoM/File_Toolkit/pull/152/files#diff-3778858fe61abd9f52663a125ab384d6ec9b8697ebf6792a88a44fadc122cdc6), modified by this PR.

After searching about this issue, I tried the following alternatives:

<details>

```cs
 try
                {
                    var fileInfo = new FileInfo(fullPath);
                    retrievedFile.Owner = fileInfo
                        .GetAccessControl()
                        .GetOwner(typeof(System.Security.Principal.SecurityIdentifier))
                        .Translate(typeof(System.Security.Principal.NTAccount))
                        .ToString();

                    success = true;
                }
                catch { }
```
</details>

and

<details>

```
                   try
                    {
                        var security = new System.Security.AccessControl.FileSecurity("C:\\temp\\FilingAdapterTest.json", System.Security.AccessControl.AccessControlSections.Owner | System.Security.AccessControl.AccessControlSections.Group | System.Security.AccessControl.AccessControlSections.Access);
                        retrievedFile.Owner = security.GetOwner(typeof(System.Security.Principal.NTAccount)).ToString();
                        success = true;
                    }
                    catch { }
```


</details>

Both throw the same exception.

Worth noting that the exception is not thrown when the FileAdapter is used from a context different than Rhino: it worked when I tried it from an unit test, like so:

```
        [Test]
        public void GetFile()
        {
            FileAdapter fa = new FileAdapter("C:\\temp\\FilingAdapterTest.json");
            fa.SetupPullRequest(null, out IRequest pullRequest);
            var result = fa.Pull(pullRequest);
        }
```

**Comment by FraserGreenroyd** [comment]
I'm closing this as this is going to require more work than anticipated to get in this side of the beta. To be picked up next milestone.

**Pull request closed without merging**
