### PR TITLE
Fixed trailing comma on creating json lists

### LINKED ISSUE #184: Error when pushing json twice to a file
#### Description:

When pushing, there is a trailing comma added to the end of a json array. So if pushing to a file twice with CreateOnly, a JsonDecode error will occur when pulling again, as there will be a ",," partway through an array.

#### Expected behaviour:

remove the trailing comma

### PR DESCRIPTION
**Pull request by Tom-Kingstone**
### Issues addressed by this PR

Closes #184 

removed adding commas on every line

### Test files

[File_Adapter-extra-Push and Pull appending content 1.zip](https://github.com/BHoM/File_Toolkit/files/14776521/File_Adapter-extra-Push.and.Pull.appending.content.1.zip)

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check installer
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by adecler — APPROVED** [review]
This fixes the problem in the test file

**Review by FraserGreenroyd — APPROVED** [review]
Thanks for jumping on this so fast @Tom-Kingstone - code reviewed and looks good, test script works from yourself and @adecler so let's put into the beta to deliver a strong artefact 😄

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Pull request merged**
